apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-okteto
  template:
    metadata:
      labels:
        app: hello-okteto
    spec:
      containers:
      - image: okteto.dev/go-hello-okteto:1.0.0
        name: hello-okteto

---

apiVersion: v1
kind: Service
metadata:
  name: hello-okteto
spec:
  type: ClusterIP
  ports:
  - name: "hello-okteto"
    port: 8080
  selector:
    app: hello-okteto

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-okteto
  annotations:
    dev.okteto.com/generate-host: hello-okteto
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-okteto
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
